### ISSUE TITLE
Chrome, OSX & Self Signed Certs

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/devnet-express-dci-issues#35]
A lot of issues by users trying access guac via Chrome and or other browsers on OSX Catalina can no longer click to easily accept the fact that the destination is a self signed certificate. 
![image](https://user-images.githubusercontent.com/18483964/76882872-a3533380-6851-11ea-92b3-fbc3bb231d18.png)

**Comment by stgreenb** [comment]
For example my Chrome is Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by annegentle** [comment]
Hi, thanks for reporting - I tested, and yep, this is the case for any self-signed certificates due to Chrome's policy. Since this policy is out of our hands and we don't have a great location to put it in the Learning Labs itself, I'll close this issue. Please share the information amongst the DevNet Express proctors as you see fit though.
